### ISSUE TITLE
More research needed

### ISSUE THREAD

**Issue by rabbiveesh** [EvanCarroll/awesome-opensource-boycott-divestment-sanctions#1]
This repository seems to assume that Israel is an apartheid state, and as such should be boycotted, divested and sanctioned.

None of these claims seem to hold, in my experience. The author of this repo should really do some research and find out facts on the ground.

**Comment by EvanCarroll** [comment]
What is your definition of an "Apartheid State"?

-----

Update this is not needed. It pretends like your experience is greater than the experiences of those living under the regime that openly declare it as an "apartheid state". Including all of the organizers and participants in the BDS movement which organize ["Apartheid Free Zones"](https://bdsmovement.net/apartheid-free-zones) and ["Israel Apartheid Week"](https://bdsmovement.net/iaw). You come here with no "research" yourself, so when you part consider reading these resources,

* http://www.itisapartheid.org/
* https://101.visualizingpalestine.org/
* https://bdsmovement.net/colonialism-and-apartheid/summary
* https://www.hrw.org/news/2021/04/27/abusive-israeli-policies-constitute-crimes-apartheid-persecution
* https://www.wsws.org/en/articles/2021/04/30/isra-a30.html
* https://stopthewall.org/
